version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: duplex_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/views:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    container_name: duplex_php
    expose:
      - "9000"
    volumes:
      - ./app/views:/var/www/html
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432

  postgres:
    build: ./postgres
    container_name: duplex_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  postgres_data:
